### ISSUE TITLE
Blitz effect not locking properly.

### ISSUE THREAD

**Issue by Prezombie** [eternaldensity/Sandcastle-Builder#1415] opened 2015-12-30 12:34 UTC
It seems that the blitz boost stays effective after locking until something else updates the sand dig rate like buying an item.

**Comment by pickten** [comment] 2015-12-30 19:42
Seems to be a duplicate of #1412, which was resolved with #1413, but the fix for which has not yet been pushed to live.

**Closed** 2015-12-30 23:19 UTC
Labels: redundant
